// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQNHcl9YVNhxq3BdAgDrfs1YMBXR8vhw',
    appId: '1:885853685428:web:a5cd644c080775498af9e1',
    messagingSenderId: '885853685428',
    projectId: 'btl-android-90ac3',
    authDomain: 'btl-android-90ac3.firebaseapp.com',
    storageBucket: 'btl-android-90ac3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tj7QXNZ7--Voa_wOwt4iJ47F2iRlupg',
    appId: '1:885853685428:android:dcbf944eccfb5e6b8af9e1',
    messagingSenderId: '885853685428',
    projectId: 'btl-android-90ac3',
    storageBucket: 'btl-android-90ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWzY0WVhjseacOUdlNM51a08P1lz9xGt0',
    appId: '1:885853685428:ios:67f93ab843293a748af9e1',
    messagingSenderId: '885853685428',
    projectId: 'btl-android-90ac3',
    storageBucket: 'btl-android-90ac3.appspot.com',
    iosBundleId: 'com.example.detectLicensePlateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWzY0WVhjseacOUdlNM51a08P1lz9xGt0',
    appId: '1:885853685428:ios:67f93ab843293a748af9e1',
    messagingSenderId: '885853685428',
    projectId: 'btl-android-90ac3',
    storageBucket: 'btl-android-90ac3.appspot.com',
    iosBundleId: 'com.example.detectLicensePlateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQNHcl9YVNhxq3BdAgDrfs1YMBXR8vhw',
    appId: '1:885853685428:web:72a9da71f1c0da678af9e1',
    messagingSenderId: '885853685428',
    projectId: 'btl-android-90ac3',
    authDomain: 'btl-android-90ac3.firebaseapp.com',
    storageBucket: 'btl-android-90ac3.appspot.com',
  );
}
